version: '3.8'

services:
  app:
    build: .
    container_name: libreria-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:libreria_db
      - SPRING_H2_CONSOLE_ENABLED=true